import re

from .ViewObject import ViewObject
from ..graphs import EtlGraphData

class EtlGraphView(ViewObject):


    PAT=re.compile(r'^graph\.svg$')
    assert(PAT.match('graph.svg'))

    def headers(self):
        return (
            ('Content-Type', 'image/svg+xml'),
        )


    def render(self, url, matches):

        data = EtlGraphData.build_graph_data_for()

        return """\
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.38.0 (20140413.2041)
 -->
<!-- Title: test Pages: 1 -->
<svg width="71pt" height="188pt"
 viewBox="0.00 0.00 71.00 188.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 184)">
<title>test</title>
<polygon fill="white" stroke="none" points="-4,4 -4,-184 67,-184 67,4 -4,4"/>
<!-- A -->
<g id="node1" class="node"><title>A</title>
<polygon fill="none" stroke="black" points="63,-180 0,-180 0,-144 63,-144 63,-180"/>
<text text-anchor="middle" x="31.5" y="-158.3" font-family="Times New Roman,serif" font-size="14.00">{{test}}</text>
</g>
<!-- B -->
<g id="node2" class="node"><title>B</title>
<ellipse fill="none" stroke="black" cx="31.5" cy="-90" rx="27" ry="18"/>
<text text-anchor="middle" x="31.5" y="-86.3" font-family="Times New Roman,serif" font-size="14.00">B</text>
</g>
<!-- A&#45;&gt;B -->
<g id="edge1" class="edge"><title>A&#45;&gt;B</title>
<path fill="none" stroke="black" d="M31.5,-143.697C31.5,-135.983 31.5,-126.712 31.5,-118.112"/>
<polygon fill="black" stroke="black" points="35.0001,-118.104 31.5,-108.104 28.0001,-118.104 35.0001,-118.104"/>
</g>
<!-- C -->
<g id="node3" class="node"><title>C</title>
<ellipse fill="none" stroke="black" cx="31.5" cy="-18" rx="27" ry="18"/>
<text text-anchor="middle" x="31.5" y="-14.3" font-family="Times New Roman,serif" font-size="14.00">C</text>
</g>
<!-- B&#45;&gt;C -->
<g id="edge2" class="edge"><title>B&#45;&gt;C</title>
<path fill="none" stroke="black" d="M31.5,-71.6966C31.5,-63.9827 31.5,-54.7125 31.5,-46.1124"/>
<polygon fill="black" stroke="black" points="35.0001,-46.1043 31.5,-36.1043 28.0001,-46.1044 35.0001,-46.1043"/>
</g>
</g>
</svg>"""
